### ISSUE TITLE
Not Installing on MAc OS

### ISSUE THREAD

**Issue by namangoel993** [s1hofmann/native-ui-toolkit#587] opened 2024-04-30 10:55 UTC
Not Found - GET https://registry.npmjs.org/@nut-tree%2fnut-js - Not found
npm ERR! 404 
npm ERR! 404  '@nut-tree/nut-js@^3.1.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by HydAu** [comment] 2024-04-30 11:36
also 4.2.0 does not seem to be in the registry

**Comment by aodekirk88** [comment] 2024-04-30 13:48
Confirmed, cannot install via NPM as of writing. Was working last night 4-29-24 ~8PM CDT

**Comment by s1hofmann** [comment] 2024-04-30 14:12
This is correct and has been explained here: https://nutjs.dev/blog/i-give-up

Prebuilt packages are no longer publicly available.

Best regards 

Simon

**Comment by thegafo** [comment] 2024-04-30 21:37
Pretty hostile, but I understand. We'll just have to fork it and publish a new NPM package.

I appreciate your open source work while it lasted. Best wishes.

**Comment by parikshit-dp** [comment] 2024-05-01 04:08
@thegafo please keep us updated on the forked version, if you do.

**Comment by davidarroyo1234** [comment] 2024-05-03 13:56
> Pretty hostile, but I understand. We'll just have to fork it and publish a new NPM package.
> 
> I appreciate your open source work while it lasted. Best wishes.

I can understand that he don't want to contribute to future versions, but remove the old ones is quite wrong IMO.

**Comment by mnn** [comment] 2024-05-03 18:57
I was recommended this project by Perplexity as a FOSS library for simulating keyboard input, I wanted to simply send a keystroke from my toy project. Unreleasing from NPM in this fashion is a very aggressive move and will burn bridges with any developer even remotely interested in open-source. I will rather try a decade old alternative, or if that (most likely) fails, I'll just use a platform specific hack than trying to make some foss-hostile project running and incur same pain on my potential users.

**Comment by thegafo** [comment] 2024-05-03 19:30
@mnn we are in the exact same boat. I was simply using this package for simulating keyboard input as well, and have had to fall back to old, bloated alternatives like `robot.js`.

Totally agree taking it off NPM was a hostile, aggressive move that will definitely burn bridges. I'm in the process of forking everything to a different project so we can at least keep the existing functionality. I will keep you posted.

**Comment by s1hofmann** [comment] 2024-05-03 22:09
> I'll just use a platform specific hack than trying to make some foss-hostile project running and incur same pain on my potential users.

Isn’t it ironic to call nut.js FOSS hostile, in an issue opened in the still open, still Apache-2.0 licensed repo that is the unmodified source of truth for the unpublished packages?

I get it, you’re upset because I removed my public packages and caused some disturbance in your projects, that’s your right.

But let me tell you one more time:

- I notified open source projects like Electron early on about the upcoming changes [1] I can only do that for projects that use nut.js I know of 🤷‍♂️
- I linked the blog post in the very top of the readme so people would see it 
- I explicitly kept the repo open
- I explicitly did not change its license 
- As I wrote in my post, I’ll still update the repo, but with a delay

If the fact that you have to build something from sources keeps you from using it, what’s the point of open source?

I decided to go this way to establish a way to keep maintaining this project in a sustainable way.
I dedicated a tremendous amount of my time and money to it over the last five and a half years and I would be happy to continue doing this without fully burning out or being treated like shit.

If you consider this project now open source hostile because of this, I’m more than happy to burn any bridge I’ll encounter.

I’ll close this issue now, since there is nothing left to add.

[1] https://discord.com/channels/745037351163527189/745037351725826080/1228311338418438214

**Closed as completed by s1hofmann** 2024-05-03 22:09 UTC

**Comment by thegafo** [comment] 2024-05-03 22:25
🤡
